/* Simple Weather Display - All info on one screen */
/* WiFi credentials loaded from .env file via load_env.py */

#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include <time.h>

// WiFi credentials (generated by load_env.py from .env file)
#include "wifi_credentials.h"

// Waveshare
#include "DEV_Config.h"
#include "EPD.h"
#include "GUI_Paint.h"

// Location
const char* LATITUDE  = "50.63";  // Lille, France
const char* LONGITUDE = "3.06";

// NTP
const char* MY_NTP_SERVER_1 = "pool.ntp.org";
const char* MY_NTP_SERVER_2 = "time.nist.gov";
const char* MY_TIMEZONE = "CET-1CEST,M3.5.0,M10.5.0/3";

static UBYTE *imageBuffer = NULL;

// Get weather text from WMO code
const char* getWeatherText(int wmo) {
  if (wmo == 0) return "Clear sky";
  else if (wmo == 1) return "Mainly clear";
  else if (wmo == 2) return "Partly cloudy";
  else if (wmo == 3) return "Overcast";
  else if (wmo >= 45 && wmo <= 48) return "Foggy";
  else if (wmo >= 51 && wmo <= 55) return "Drizzle";
  else if (wmo >= 61 && wmo <= 65) return "Rain";
  else if (wmo >= 71 && wmo <= 77) return "Snow";
  else if (wmo >= 80 && wmo <= 82) return "Showers";
  else if (wmo >= 95) return "Thunderstorm";
  return "Unknown";
}

// Draw everything on one screen
void drawWeatherScreen(float temp, int humidity, int wmo, float wind, 
                       float tempMax, float tempMin,
                       float hourlyTemps[4], int hourlyCodes[4], int hourlyHours[4]) {
  Paint_Clear(WHITE);
  char buf[64];
  
  // ===== HEADER =====
  Paint_DrawString_EN(10, 5, "Lille, France", &Font20, BLACK, WHITE);
  Paint_DrawLine(0, 30, 800, 30, BLACK, DOT_PIXEL_1X1, LINE_STYLE_SOLID);
  
  // ===== LEFT SIDE: Current Weather =====
  // Big temperature
  snprintf(buf, sizeof(buf), "%.1f", temp);
  Paint_DrawString_EN(20, 45, buf, &Font24, BLACK, WHITE);
  Paint_DrawString_EN(20, 80, "C", &Font16, BLACK, WHITE);
  
  // Weather condition
  Paint_DrawString_EN(20, 110, getWeatherText(wmo), &Font16, BLACK, WHITE);
  
  // Details
  snprintf(buf, sizeof(buf), "Humidity: %d%%", humidity);
  Paint_DrawString_EN(20, 140, buf, &Font12, BLACK, WHITE);
  
  snprintf(buf, sizeof(buf), "Wind: %.0f km/h", wind);
  Paint_DrawString_EN(20, 160, buf, &Font12, BLACK, WHITE);
  
  // Tomorrow forecast
  Paint_DrawLine(0, 190, 300, 190, BLACK, DOT_PIXEL_1X1, LINE_STYLE_SOLID);
  Paint_DrawString_EN(20, 200, "Tomorrow:", &Font12, BLACK, WHITE);
  snprintf(buf, sizeof(buf), "H: %.0fC  L: %.0fC", tempMax, tempMin);
  Paint_DrawString_EN(20, 220, buf, &Font12, BLACK, WHITE);
  
  // ===== RIGHT SIDE: Hourly Forecast =====
  Paint_DrawLine(320, 30, 320, 250, BLACK, DOT_PIXEL_1X1, LINE_STYLE_SOLID);
  Paint_DrawString_EN(340, 40, "Next hours:", &Font16, BLACK, WHITE);
  
  // 4 hours forecast
  for (int i = 0; i < 4; i++) {
    int y = 70 + i * 45;
    
    // Hour
    snprintf(buf, sizeof(buf), "%02d:00", hourlyHours[i]);
    Paint_DrawString_EN(340, y, buf, &Font12, BLACK, WHITE);
    
    // Temperature
    snprintf(buf, sizeof(buf), "%.0fC", hourlyTemps[i]);
    Paint_DrawString_EN(420, y, buf, &Font16, BLACK, WHITE);
    
    // Weather (simplified)
    const char* code = "";
    if (hourlyCodes[i] == 0) code = "Clear";
    else if (hourlyCodes[i] <= 3) code = "Cloudy";
    else if (hourlyCodes[i] <= 65) code = "Rain";
    else code = "Snow";
    
    Paint_DrawString_EN(500, y, code, &Font12, BLACK, WHITE);
  }
  
  // ===== FOOTER =====
  Paint_DrawLine(0, 250, 800, 250, BLACK, DOT_PIXEL_1X1, LINE_STYLE_SOLID);
  Paint_DrawString_EN(10, 255, "Open-Meteo Weather", &Font12, BLACK, WHITE);
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("\n=== Weather Display ===");
  
  // Initialize display
  DEV_Module_Init();
  EPD_7IN5_V2_Init();
  EPD_7IN5_V2_Clear();
  DEV_Delay_ms(500);
  
  UWORD Imagesize = ((EPD_7IN5_V2_WIDTH % 8 == 0) ? 
                     (EPD_7IN5_V2_WIDTH / 8) : 
                     (EPD_7IN5_V2_WIDTH / 8 + 1)) * EPD_7IN5_V2_HEIGHT;
  imageBuffer = (UBYTE *)malloc(Imagesize);
  Paint_NewImage(imageBuffer, EPD_7IN5_V2_WIDTH, EPD_7IN5_V2_HEIGHT, 0, WHITE);
  
  // Initial screen
  Paint_Clear(WHITE);
  Paint_DrawString_EN(10, 10, "Connecting WiFi...", &Font16, BLACK, WHITE);
  EPD_7IN5_V2_Display(imageBuffer);
  
  // WiFi
  WiFi.begin(WIFI_SSID_VALUE, WIFI_PASSWORD_VALUE);
  int retries = 0;
  while (WiFi.status() != WL_CONNECTED && retries < 30) {
    delay(500);
    Serial.print(".");
    retries++;
  }
  
  if (WiFi.status() != WL_CONNECTED) {
    Paint_Clear(WHITE);
    Paint_DrawString_EN(10, 10, "WiFi Failed!", &Font16, BLACK, WHITE);
    EPD_7IN5_V2_Display(imageBuffer);
    delay(5000);
    ESP.restart();
  }
  Serial.println("\nWiFi OK");
  
  // NTP
  configTzTime(MY_TIMEZONE, MY_NTP_SERVER_1, MY_NTP_SERVER_2);
  struct tm timeinfo;
  int ntpRetries = 0;
  while (!getLocalTime(&timeinfo) && ntpRetries < 10) {
    delay(500);
    ntpRetries++;
  }
  
  // Fetch data
  Paint_Clear(WHITE);
  Paint_DrawString_EN(10, 10, "Fetching data...", &Font16, BLACK, WHITE);
  EPD_7IN5_V2_Display(imageBuffer);
  
  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  
  // API - Current + Daily + Hourly
  String url = "https://api.open-meteo.com/v1/forecast?latitude=" + String(LATITUDE) + 
               "&longitude=" + String(LONGITUDE) + 
               "&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m" +
               "&daily=temperature_2m_max,temperature_2m_min" +
               "&hourly=temperature_2m,weather_code" +
               "&timezone=auto&forecast_days=2";
  
  http.begin(client, url);
  int code = http.GET();
  
  if (code == 200) {
    String payload = http.getString();
    
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, payload);
    
    if (!error) {
      // Current data
      float temp = doc["current"]["temperature_2m"];
      int humidity = doc["current"]["relative_humidity_2m"];
      int wmo = doc["current"]["weather_code"];
      float wind = doc["current"]["wind_speed_10m"];
      
      // Tomorrow forecast
      float tempMax = doc["daily"]["temperature_2m_max"][1];
      float tempMin = doc["daily"]["temperature_2m_min"][1];
      
      // Hourly forecast (next 4 hours)
      float hourlyTemps[4];
      int hourlyCodes[4];
      int hourlyHours[4];
      
      getLocalTime(&timeinfo);
      int currentHour = timeinfo.tm_hour;
      
      for (int i = 0; i < 4; i++) {
        hourlyTemps[i] = doc["hourly"]["temperature_2m"][currentHour + i + 1];
        hourlyCodes[i] = doc["hourly"]["weather_code"][currentHour + i + 1];
        hourlyHours[i] = (currentHour + i + 1) % 24;
      }
      
      // Draw everything on one screen
      drawWeatherScreen(temp, humidity, wmo, wind, tempMax, tempMin,
                        hourlyTemps, hourlyCodes, hourlyHours);
      EPD_7IN5_V2_Display(imageBuffer);
      
      Serial.printf("Temp: %.1fC, Humidity: %d%%\n", temp, humidity);
    } else {
      Paint_Clear(WHITE);
      Paint_DrawString_EN(10, 10, "JSON Error", &Font16, BLACK, WHITE);
      EPD_7IN5_V2_Display(imageBuffer);
    }
  } else {
    Paint_Clear(WHITE);
    Paint_DrawString_EN(10, 10, "API Error", &Font16, BLACK, WHITE);
    char buf[32];
    snprintf(buf, sizeof(buf), "Code: %d", code);
    Paint_DrawString_EN(10, 40, buf, &Font16, BLACK, WHITE);
    EPD_7IN5_V2_Display(imageBuffer);
  }
  
  http.end();
  WiFi.disconnect();
  
  Serial.println("Done - sleeping 30 min");
  
  // Sleep 30 minutes
  esp_sleep_enable_timer_wakeup(1800ULL * 1000000ULL);
  esp_deep_sleep_start();
}

void loop() {
}
