/* Weather Display - Phase 1 Layout (Luke Marzen style) */
/* 800x480 layout with widget grid, 5-day forecast, hourly graph */

#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include <time.h>
#include "client_utils.h"  // For parseIso8601

// WiFi credentials (generated by load_env.py from .env file)
#include "wifi_credentials.h"

// Renderer with Phase 1 layout
#include "renderer.h"
#include "api_response.h"

// Location: Lille, France
const char* LATITUDE  = "50.63";
const char* LONGITUDE = "3.06";
const char* CITY_NAME = "Lille";

// NTP
const char* MY_NTP_SERVER_1 = "pool.ntp.org";
const char* MY_NTP_SERVER_2 = "time.nist.gov";
const char* MY_TIMEZONE = "CET-1CEST,M3.5.0,M10.5.0/3";

// Sleep duration (seconds)
const uint64_t MY_SLEEP_DURATION = 1800; // 30 minutes

// Fetch and parse Open-Meteo data
bool fetchWeatherData(owm_current_t &current, owm_daily_t *daily, owm_hourly_t *hourly, 
                      int &rssi, tm &timeInfo) {
  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  
  // API URL - get current, daily (7 days), hourly (48 hours)
  String url = "https://api.open-meteo.com/v1/forecast?latitude=" + String(LATITUDE) + 
               "&longitude=" + String(LONGITUDE) + 
               "&current=temperature_2m,relative_humidity_2m,weather_code,"
               "wind_speed_10m,pressure_msl,apparent_temperature,is_day" +
               "&daily=temperature_2m_max,temperature_2m_min,weather_code,"
               "sunrise,sunset" +
               "&hourly=temperature_2m,weather_code" +
               "&timezone=auto&forecast_days=7&past_days=0";
  
  Serial.println("Fetching: " + url);
  http.begin(client, url);
  int code = http.GET();
  
  if (code != 200) {
    Serial.printf("API Error: %d\n", code);
    http.end();
    return false;
  }
  
  String payload = http.getString();
  http.end();
  
  // Parse JSON
  JsonDocument doc;
  DeserializationError error = deserializeJson(doc, payload);
  
  if (error) {
    Serial.println("JSON parse error");
    return false;
  }
  
  // Fill current conditions
  current.temp = doc["current"]["temperature_2m"];
  current.feels_like = doc["current"]["apparent_temperature"];
  current.humidity = doc["current"]["relative_humidity_2m"];
  current.wind_speed = doc["current"]["wind_speed_10m"];
  current.pressure = doc["current"]["pressure_msl"];
  int wmoCode = doc["current"]["weather_code"];
  current.weather.main = "Clouds"; // Simplified
  current.weather.id = wmoCode;
  
  // Sunrise/sunset (from daily[0])
  const char* sunriseStr = doc["daily"]["sunrise"][0];
  const char* sunsetStr = doc["daily"]["sunset"][0];
  
  // Parse ISO time to timestamp
  current.sunrise = parseIso8601(sunriseStr);
  current.sunset = parseIso8601(sunsetStr);
  
  // Fill daily forecast (5 days)
  time_t now = time(nullptr);
  struct tm today_tm;
  localtime_r(&now, &today_tm);
  
  for (int i = 0; i < 5; i++) {
    daily[i].temp.max = doc["daily"]["temperature_2m_max"][i];
    daily[i].temp.min = doc["daily"]["temperature_2m_min"][i];
    int dailyWmo = doc["daily"]["weather_code"][i];
    daily[i].weather.id = dailyWmo;
    daily[i].weather.main = "Clouds";
    
    // Calculate timestamp for each day (today + i days at noon)
    struct tm day_tm = today_tm;
    day_tm.tm_mday += i;
    day_tm.tm_hour = 12;
    day_tm.tm_min = 0;
    day_tm.tm_sec = 0;
    mktime(&day_tm);  // Normalize
    daily[i].dt = mktime(&day_tm);
    
    const char* dailySunrise = doc["daily"]["sunrise"][i];
    daily[i].sunrise = parseIso8601(dailySunrise);
    const char* dailySunset = doc["daily"]["sunset"][i];
    daily[i].sunset = parseIso8601(dailySunset);
  }
  
  // Fill hourly forecast (next 24 hours from current time)
  getLocalTime(&timeInfo);
  int currentHour = timeInfo.tm_hour;
  
  for (int i = 0; i < 24; i++) {
    hourly[i].temp = doc["hourly"]["temperature_2m"][currentHour + i];
    int hourlyWmo = doc["hourly"]["weather_code"][currentHour + i];
    hourly[i].weather.id = hourlyWmo;
    hourly[i].weather.main = "Clouds";
    hourly[i].weather.description = "";
    
    // Calculate timestamp for this hour
    time_t now = time(nullptr);
    hourly[i].dt = now + (i + 1) * 3600;
  }
  
  rssi = WiFi.RSSI();
  return true;
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("\n=== Weather Display - Phase 1 Layout ===");
  
  // Initialize display
  initDisplay();
  
  // Clear screen and show loading
  Paint_Clear(WHITE);
  Paint_DrawString_EN(10, 10, "Connecting WiFi...", &Font16, BLACK, WHITE);
  refreshDisplay();
  
  // WiFi
  WiFi.begin(WIFI_SSID_VALUE, WIFI_PASSWORD_VALUE);
  int retries = 0;
  while (WiFi.status() != WL_CONNECTED && retries < 30) {
    delay(500);
    Serial.print(".");
    retries++;
  }
  
  if (WiFi.status() != WL_CONNECTED) {
    Paint_Clear(WHITE);
    Paint_DrawString_EN(10, 10, "WiFi Failed!", &Font16, BLACK, WHITE);
    refreshDisplay();
    delay(5000);
    ESP.restart();
  }
  Serial.println("\nWiFi OK");
  
  // NTP
  configTzTime(MY_TIMEZONE, MY_NTP_SERVER_1, MY_NTP_SERVER_2);
  struct tm timeInfo;
  int ntpRetries = 0;
  while (!getLocalTime(&timeInfo) && ntpRetries < 10) {
    delay(500);
    ntpRetries++;
  }
  
  // Show fetching message
  Paint_Clear(WHITE);
  Paint_DrawString_EN(10, 10, "Fetching weather...", &Font16, BLACK, WHITE);
  refreshDisplay();
  
  // Allocate data structures on heap (avoid stack overflow)
  owm_current_t *current = new owm_current_t();
  owm_daily_t *daily = new owm_daily_t[5]();
  owm_hourly_t *hourly = new owm_hourly_t[24]();
  
  int rssi = 0;
  bool success = fetchWeatherData(*current, daily, hourly, rssi, timeInfo);
  
  if (success) {
    // Clear screen for main layout
    Paint_Clear(WHITE);
    
    // Build date string
    char dateStr[32];
    strftime(dateStr, sizeof(dateStr), "%a, %d %b %Y", &timeInfo);
    
    // Build refresh time string
    char refreshStr[32];
    strftime(refreshStr, sizeof(refreshStr), "Updated %H:%M", &timeInfo);
    
    // Draw Phase 1 Layout
    // 1. Location and date (top right)
    drawLocationDate(CITY_NAME, dateStr);
    
    // 2. Current conditions (left side with widget grid)
    owm_resp_air_pollution_t dummyAir = {};
    drawCurrentConditions(*current, daily[0], hourly[0], dummyAir, 0.0f, 0.0f);
    
    // 3. 5-day forecast (top right, below location)
    drawForecast(daily, timeInfo);
    
    // 4. Hourly outlook graph (bottom right)
    drawOutlookGraph(hourly, daily, timeInfo);
    
    // 5. Status bar (bottom)
    drawStatusBar("", refreshStr, rssi, UINT32_MAX);
    
    // Refresh display
    refreshDisplay();
    
    Serial.printf("Temp: %.1fC, Feels: %.1fC\n", current->temp, current->feels_like);
  } else {
    // Error screen
    Paint_Clear(WHITE);
    Paint_DrawString_EN(10, 10, "Failed to fetch weather", &Font16, BLACK, WHITE);
    refreshDisplay();
  }
  
  // Cleanup
  delete current;
  delete[] daily;
  delete[] hourly;
  
  WiFi.disconnect();
  
  Serial.println("Done - sleeping 30 min");
  
  // Deep sleep
  esp_sleep_enable_timer_wakeup(MY_SLEEP_DURATION * 1000000ULL);
  esp_deep_sleep_start();
}

void loop() {
  // Not used - deep sleep restart
}
